//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 06:27:45 PM EDT 
//


package com.in28minutes.courses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DogDetails" type="{http://in28minutes.com/courses}DogDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dogDetails"
})
@XmlRootElement(name = "GetDogDetailsResponse")
public class GetDogDetailsResponse {

    @XmlElement(name = "DogDetails", required = true)
    protected DogDetails dogDetails;

    /**
     * Gets the value of the dogDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DogDetails }
     *     
     */
    public DogDetails getDogDetails() {
        return dogDetails;
    }

    /**
     * Sets the value of the dogDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DogDetails }
     *     
     */
    public void setDogDetails(DogDetails value) {
        this.dogDetails = value;
    }

}
